version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      # Use a clean installation approach
      - cd frontend
      - npm ci --omit=dev
      - npm rebuild
      - cd ../backend
      - npm ci --omit=dev
      - cd ..

  build:
    commands:
      - echo "Building application..."
      - cd frontend
      - npx vite build
      - cd ..
      - mkdir -p dist

  post_build:
    commands:
      - cp -r frontend/dist dist/frontend
      - cp -r backend dist/backend
      - rm -rf dist/backend/node_modules

artifacts:
  files:
    - '**/*'
  base-directory: dist